# Generated by Django 2.1.3 on 2018-12-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=200)),
                ('db_vendor', models.CharField(max_length=50)),
                ('backup_status', models.CharField(choices=[('0', 'GOOD'), ('1', 'BAD')], max_length=1)),
                ('backup_start_time', models.DateField()),
                ('backup_finish_time', models.DateField()),
                ('latest_backup', models.DateField()),
            ],
        ),
    ]
