# Generated by Django 2.1.3 on 2018-12-05 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, choices=[('started', 'STARTED'), ('done', 'DONE')], max_length=1)),
                ('start_time', models.DateField()),
                ('finish_time', models.DateField(blank=True)),
                ('duration', models.CharField(blank=True, max_length=20)),
                ('filename', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='host',
            old_name='host_name',
            new_name='host',
        ),
        migrations.RenameField(
            model_name='host',
            old_name='db_vendor',
            new_name='vendor',
        ),
        migrations.RemoveField(
            model_name='host',
            name='backup_finish_time',
        ),
        migrations.RemoveField(
            model_name='host',
            name='backup_start_time',
        ),
        migrations.RemoveField(
            model_name='host',
            name='backup_status',
        ),
        migrations.RemoveField(
            model_name='host',
            name='latest_backup',
        ),
        migrations.AddField(
            model_name='backup',
            name='host_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Host'),
        ),
    ]
