# Generated by Django 2.1.3 on 2018-12-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20181205_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='backup',
            name='finish_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='backup',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
