# Generated by Django 2.1.3 on 2018-12-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20181205_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='state',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
