# Generated by Django 2.1.3 on 2018-12-09 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20181206_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='host_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='dashboard.Host'),
        ),
    ]
