# Generated by Django 2.1.3 on 2018-12-10 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20181209_0916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backup',
            options={'ordering': ['-id']},
        ),
    ]
